package com.fioletowi.farma.auth;

import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.springframework.data.annotation.CreatedDate;
import org.springframework.data.jpa.domain.support.AuditingEntityListener;

import java.time.LocalDateTime;

@Builder
@Data
@AllArgsConstructor
@NoArgsConstructor
@Entity
@Table(name = "token")
@EntityListeners(AuditingEntityListener.class)
public class Token {

    /**
     * Primary key for the token entity.
     * Automatically generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * The token string used for authentication or password reset.
     * Cannot be null.
     */
    @Column(name = "token", nullable = false)
    private String token;

    /**
     * Email address associated with this token.
     * Cannot be null.
     */
    @Column(name = "email", nullable = false)
    private String email;

    /**
     * Date and time when the token expires.
     * Cannot be null.
     */
    @Column(name = "expired_at", nullable = false)
    private LocalDateTime expiredAt;

    /**
     * Date and time when the token was created.
     * Set automatically when the entity is created and not updatable afterwards.
     */
    @Column(name = "created_at", updatable = false, nullable = false)
    @CreatedDate
    private LocalDateTime createdAt;

}
